"""migration

Revision ID: 2f4151b70bdc
Revises: 973ab0521ee4
Create Date: 2021-07-13 15:00:19.717630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f4151b70bdc'
down_revision = '973ab0521ee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('published', sa.Boolean(), server_default='false', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'published')
    # ### end Alembic commands ###
