"""migration

Revision ID: 5ecd21f0993c
Revises: ec57da0449a1
Create Date: 2021-07-21 19:31:06.182589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ecd21f0993c'
down_revision = 'ec57da0449a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'business', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'business', type_='unique')
    # ### end Alembic commands ###
