"""migration

Revision ID: a81c1d306ba5
Revises: 2f4151b70bdc
Create Date: 2021-07-14 21:46:59.735152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a81c1d306ba5'
down_revision = '2f4151b70bdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('in_menu', sa.Boolean(), server_default='false', nullable=True))
    op.drop_column('items', 'published')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('published', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_column('items', 'in_menu')
    # ### end Alembic commands ###
