"""migration

Revision ID: c02b24556790
Revises: 5ecd21f0993c
Create Date: 2021-07-21 19:31:24.582737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c02b24556790'
down_revision = '5ecd21f0993c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
