name: Run isort
on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: jamescurtin/isort-action@master
        with:
            requirementsFiles: "requirements/_development.txt"
